"""empty message

Revision ID: 0335c8744390
Revises: 23db34895c85
Create Date: 2023-10-11 11:46:08.802704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0335c8744390"
down_revision = "23db34895c85"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workbench_app_engine_metadata")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workbench_app_engine_metadata",
        sa.Column("instance_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "dataset_identifier", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("bucket_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("vm_image", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("region", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("disk_size", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("machine_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="workbench_app_engine_metadata_pkey"),
    )
    # ### end Alembic commands ###
