"""add_sharing_metadata

Revision ID: 7f6ecf630e82
Revises: b5d69f2e87da
Create Date: 2023-11-02 09:54:48.534964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7f6ecf630e82"
down_revision = "b5d69f2e87da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sharing_connections",
        sa.Column("sharer_email", sa.String(), nullable=False),
        sa.Column("accessor_email", sa.String(), nullable=False),
        sa.Column("bucket_name", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column(
            "state", sa.Enum("SHARED", "REVOKED", name="sharingstate"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sharing_connections")
    # ### end Alembic commands ###
