"""change field name

Revision ID: 9b00a17454e8
Revises: e04b19d8a1cb
Create Date: 2023-07-21 09:58:05.088784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b00a17454e8"
down_revision = "e04b19d8a1cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workbench_workbench_activities",
        sa.Column("invoker_email", sa.String(), nullable=False),
    )
    op.drop_column("workbench_workbench_activities", "invoker_username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workbench_workbench_activities",
        sa.Column(
            "invoker_username", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("workbench_workbench_activities", "invoker_email")
    # ### end Alembic commands ###
