"""empty message

Revision ID: bfb83fc35bec
Revises: 1053e575b4ef
Create Date: 2025-05-06 18:18:52.346449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfb83fc35bec'
down_revision = '1053e575b4ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharing_access_requests',
    sa.Column('requester_email', sa.String(), nullable=False),
    sa.Column('bucket_name', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('requested_permissions', sa.Enum('READ_WRITE', 'READ', name='bucketpermissions'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='bucketrequeststatus'), nullable=False),
    sa.Column('sharer_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('workbench_monitoring_data', 'dataset_identifier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workbench_monitoring_data', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workbench_monitoring_data', 'workbench_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('idx_project_name', table_name='workbench_monitoring_data')
    op.drop_index('idx_user_email', table_name='workbench_monitoring_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_email', 'workbench_monitoring_data', ['user_email'], unique=False)
    op.create_index('idx_project_name', 'workbench_monitoring_data', ['dataset_identifier'], unique=False)
    op.alter_column('workbench_monitoring_data', 'workbench_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workbench_monitoring_data', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workbench_monitoring_data', 'dataset_identifier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('sharing_access_requests')
    # ### end Alembic commands ###
