"""make fields nullable

Revision ID: e04b19d8a1cb
Revises: 13a4128a89fe
Create Date: 2023-07-20 14:33:08.018123

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "e04b19d8a1cb"
down_revision = "13a4128a89fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workbench_workbench_activities",
        "build_status",
        existing_type=postgresql.ENUM(
            "STATUS_UNKNOWN",
            "PENDING",
            "QUEUED",
            "WORKING",
            "SUCCESS",
            "FAILURE",
            "INTERNAL_ERROR",
            "TIMEOUT",
            "CANCELLED",
            "EXPIRED",
            name="status",
        ),
        nullable=True,
    )
    op.alter_column(
        "workbench_workbench_activities",
        "build_error_information",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workbench_workbench_activities",
        "build_error_information",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "workbench_workbench_activities",
        "build_status",
        existing_type=postgresql.ENUM(
            "STATUS_UNKNOWN",
            "PENDING",
            "QUEUED",
            "WORKING",
            "SUCCESS",
            "FAILURE",
            "INTERNAL_ERROR",
            "TIMEOUT",
            "CANCELLED",
            "EXPIRED",
            name="status",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###
