"""Create initial CloudIdentity.

Revision ID: 0d6aeb5e265c
Revises:
Create Date: 2023-04-18 10:42:23.362768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0d6aeb5e265c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cloud_identity",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("(gen_random_uuid())"),
            nullable=False,
        ),
        sa.Column("primary_email", sa.String(length=256), nullable=True),
        sa.Column("is_configured", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("primary_email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cloud_identity")
    # ### end Alembic commands ###
