from os import environ

PROJECT_ID = environ["PROJECT_ID"]
BILLING_ACCOUNT_CREATOR_GROUP_ID = environ["BILLING_ACCOUNT_CREATOR_GROUP_ID"]

DATASTORE_KIND = "cloud_identity"
ORGANIZATION_DOMAIN = "healthdatanexus.ai"
DEFAULT_PASSWORD_LENGTH = 20
